In [1]:
import numpy as np

# ランダムな3次元ベクトルを生成
pi = np.random.rand(3)

# G * pi = pi を満たす G を計算
# G = pi * pi^T / (pi^T * pi) とすると、この条件を満たす行列 G が得られる
# pi^T * pi は内積であるため、スカラー値になる
G = np.outer(pi, pi) / np.dot(pi, pi)

# 結果の確認
print("Random vector pi:")
print(pi)
print("\nMatrix G:")
print(G)
print("\nCheck G * pi = pi:")
print(np.dot(G, pi))  # G * pi が pi に等しいか確認


Random vector pi:
[0.22638162 0.97848945 0.83077243]

Matrix G:
[[0.03016626 0.13038763 0.11070374]
 [0.13038763 0.56357454 0.47849487]
 [0.11070374 0.47849487 0.40625921]]

Check G * pi = pi:
[0.22638162 0.97848945 0.83077243]


In [4]:
import numpy as np

# ランダムな3次元ベクトルを生成
pi = np.random.rand(3)

# 射影行列 (プロジェクション行列) を計算
P = np.outer(pi, pi) / np.dot(pi, pi)

# pi に垂直な成分を生成する関数
def generate_null_space_matrix(pi, scale=1.0):
    # pi に垂直なベクトルを生成 (ランダムな方向)
    null_vector = np.random.rand(3)
    null_vector -= np.dot(null_vector, pi) / np.dot(pi, pi) * pi  # pi 方向を除去
    null_vector /= np.linalg.norm(null_vector)  # 正規化

    # 外積で null 成分の行列を生成
    N = scale * np.outer(null_vector, null_vector)
    return N

# G の候補を生成
candidates = []
for _ in range(5):
    # ランダムな垂直成分を持つ行列 N を生成
    N = generate_null_space_matrix(pi, scale=np.random.rand() * 0.1)
    G = P + N
    candidates.append(G)

# 結果の表示
print("Random vector pi:")
print(pi)
print("\nCandidates for G:")
for i, G in enumerate(candidates):
    print(f"\nCandidate {i + 1}:")
    print(G)
    print("\nCheck G * pi = pi:")
    print(np.dot(G, pi))  # G * pi が pi と等しいか確認


Random vector pi:
[0.02839453 0.26320973 0.57727532]

Candidates for G:

Candidate 1:
[[0.00214814 0.01526288 0.04212236]
 [0.01526288 0.24331835 0.34425963]
 [0.04212236 0.34425963 0.84096232]]

Check G * pi = pi:
[0.02839453 0.26320973 0.57727532]

Candidate 2:
[[0.00487938 0.02577976 0.03719283]
 [0.02577976 0.19001487 0.36804615]
 [0.03719283 0.36804615 0.83035928]]

Check G * pi = pi:
[0.02839453 0.26320973 0.57727532]

Candidate 3:
[[0.00990008 0.03052078 0.03478419]
 [0.03052078 0.18996497 0.36783571]
 [0.03478419 0.36783571 0.8305737 ]]

Check G * pi = pi:
[0.02839453 0.26320973 0.57727532]

Candidate 4:
[[0.02085817 0.01625992 0.04074746]
 [0.01625992 0.17204064 0.37670979]
 [0.04074746 0.37670979 0.82623423]]

Check G * pi = pi:
[0.02839453 0.26320973 0.57727532]

Candidate 5:
[[0.0143518  0.03465011 0.03268245]
 [0.03465011 0.19280394 0.36633817]
 [0.03268245 0.36633817 0.83135989]]

Check G * pi = pi:
[0.02839453 0.26320973 0.57727532]
